# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.4.1
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Install MS Edge
      uses: browser-actions/setup-edge@latest
    - name: Build with Maven
      run: >
        mvn -B package
        --file pom.xml
        clean install
        -DskipTests
    - name: Maven test
      run: >
        mvn -B package
        -- file pom.xml
        clean test
        cluecumber-report:reporting 
        -DtestSuite=test-suites/testng.yaml 
        -Dstage=config-dev.yaml 
        -DsuiteThreads=1 
        -DgithubToken=${{ secrets.GITHUB_TOKEN }}        
