# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        browser: [chromium, firefox, edge]
        os: [windows, ubuntu, macos]
        version: [latest, latest, latest]
    runs-on: ${{ matrix.os }}
  
    steps:
    
    - uses: actions/checkout@v3
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    - run: yarn install --frozen-lockfile      

    - uses: browser-actions/setup-firefox@latest
      if: matrix.browser == 'firefox'
      with:
          firefox-version: "latest"
    - uses: browser-actions/setup-chromium@latest
      if: matrix.browser == 'chromium' && matrix.os == 'windows'
    - uses: browser-actions/setup-edge@latest
      if: matrix.browser == 'edge'

    - name: Run tests on Firefox
      if: matrix.browser == 'firefox'
      run: |
          yarn test --browsers=Firefox
    - name: Run test on Chromium
      if: matrix.browser == 'chromium'
      run: |
          $Env:CHROMIUM_BIN = "chrome"
          yarn test --browsers=Chromium
    - name: Run test on Microsoft Edge
      if: matrix.browser == 'edge'
      run: |
          $Env:EDGE_BIN = "msedge.exe"
          yarn test --browsers=Edge      
    - name: Set up JDK 17
      uses: actions/setup-java@v3.4.1
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
    - name: Install MS Edge
      uses: browser-actions/setup-edge@latest
    - name: Build with Maven
      run: >
        mvn -B package
        --file pom.xml
        clean install
        -DskipTests
    - name: Maven test
      run: >
        mvn -B package
        -- file pom.xml
        clean test
        cluecumber-report:reporting 
        -DtestSuite=test-suites/testng.yaml 
        -Dstage=config-dev.yaml 
        -DsuiteThreads=1 
        -DgithubToken=${{ secrets.GITHUB_TOKEN }}        
